feat: add support to CommonJS
gamedig/node-gamedig pull request #519
Opened 2024-01-27 22:37 UTC by GuilhermeWerner

### This PR adds

Support for CommonJS modules using esbuild.

Closes #517

### Explanation

To support projects that use ESModules and CommonJS at the same time, it is possible to use a bundler to transpile the code.

In this PR, esbuild was used, available in the file `tools/esbuild.js`, when executing this file a lib bundle converted to CommonJS is generated, which can then be used by projects that use `require`.

So that the npm package knows which file should be used according to the project type, the `main` directive of `package.json` was replaced by `exports`, which determines the two files that will be exported according to the type.

```json
"exports": {
    "import": "./lib/index.js",
    "require": "./dist/index.cjs"
},
```

The bundler settings can be changed in the script, in this PR the transpiled file is created in the `dist/index.cjs` folder, however it is up to the lib maintainers to decide where this file should be, just remember that this file was generated by the bundler and It has relatively low readability and should be ignored from the repository.

To facilitate the package publishing process on NPM, scripts were created to run the build automatically when the package is installed (prepare).

The examples were also changed to demonstrate use with require and import.

### Detail about the got dependency

The http client library that is used only supports ESModules (https://github.com/sindresorhus/got/issues/1789).
![image](https://github.com/gamedig/node-gamedig/assets/26710260/601d56bc-5fa2-4abf-9036-40cbd8b3374c)

To fix this, it is included in the bundle so that esbuild can convert its source code. The downside of this is that the bundle file becomes much larger.

2024-01-28 16:52 UTC, CosminPerRam requested changes
LGTM, thanks bunch.

Edit: forgot to mention to add a line in the changelog file.

2024-01-28 16:52 UTC, CosminPerRam commented on examples/require.cjs
> +// Instead of '../lib/index.js' you would have here 'gamedig'.
`../lib/index.js` should be `../dist/index.cjs` here.

2024-01-28 16:52 UTC, CosminPerRam commented on package.json
> +        "prepare ": "npm run build",
There is a trailing whitespace after the word `prepare`.

2024-01-28 16:52 UTC, CosminPerRam commented on tools/esbuild.js
> +  target: 'node14',
target should be node16 as we have moved to it.

2024-01-28 16:52 UTC, CosminPerRam commented on tools/esbuild.js
> +build(buildConfig).then(() => { }).catch(() => { process.exit(1) })
Please add a trailing newline (:

2024-01-28 16:59 UTC, CosminPerRam commented
Thanks bunch, just a note to have them for future references:
> Detail about the got dependency

This is unfortunate, but we'll have to go with this for now.

I too think that the abrupt move to ESM wasn't exactly the best choice for v5, but I think it'll be fair to completely remove support for it for v6 (as by then we would already be passing 3 years since stable esm support).

2024-01-28 19:05 UTC, CosminPerRam requested changes
Forgot to mention to add a line in the changelog file

2024-01-29 11:55 UTC, GuilhermeWerner commented
> Forgot to mention to add a line in the changelog file

I always forget the changelog 🫠

2024-01-29 17:55 UTC, podrivo commented
@GuilhermeWerner Sorry, a last minute conflict... :(

2024-01-29 20:55 UTC, CosminPerRam approved these changes

2024-01-29 20:55 UTC, merged