feat: Add Grand Theft Auto V - RAGE MP support
gamedig/node-gamedig pull request #576
Opened 2024-06-19 15:25 UTC by xCausxn

Implements support for getting server info from the rage mp server list.

2024-06-19 15:27 UTC, xCausxn commented
@CosminPerRam I opted to just return the entry server result entry as the "raw" field. Partly due to the fact potential info for the nested entry is available at the top level.

We could however remove excess entries and move the servers[X] entry to the top level for our case.

2024-06-20 08:17 UTC, CosminPerRam approved these changes
Great stuff!

2024-06-20 08:17 UTC, CosminPerRam commented
> Partly due to the fact potential info for the nested entry is available at the top level.

We can leave it this way.

2024-06-21 23:40 UTC, CosminPerRam requested changes

2024-06-21 23:40 UTC, CosminPerRam commented on CHANGELOG.md
> +* Node.js 6 is now required
Hmmm, seems like a stray change here?

2024-06-21 23:40 UTC, CosminPerRam commented on lib/games.js
> +  },
Please add this to properly make the table generator reference the note:
```
extra: {
  doc_notes: 'gta5r'
}
```

Like as in:
```
  trackmaniaforever: {
    name: 'Trackmania Forever',
    release_year: 2008,
    options: {
      port: 2350,
      port_query: 5000,
      protocol: 'nadeo'
    },
    extra: {
      doc_notes: 'nadeo'
    }
  },
  ```
```

2024-06-24 08:18 UTC, CosminPerRam approved these changes

2024-06-24 08:18 UTC, merged