Fix alt:V Multiplayer naming as per their branding
gamedig/node-gamedig pull request #601
Opened 2024-08-09 10:45 UTC by xCausxn

Fixes #600

2024-08-09 11:05 UTC, xCausxn commented
I can modify the ID to be `gta5am` and add an old_id to be be `gta5a` to satisfy the ID test. thoughts @CosminPerRam

2024-08-10 18:33 UTC, CosminPerRam commented
@xCausxn yep, please do as its needed

2024-08-10 18:46 UTC, xCausxn commented
Sorted

2024-08-10 18:47 UTC, CosminPerRam requested changes

2024-08-10 18:47 UTC, CosminPerRam commented on GAMES_LIST.md
> +### <a name="gta5a"></a> Grand Theft Auto V - alt:V Multiplayer
`name` should be `gta5am` now

2024-08-10 18:50 UTC, CosminPerRam approved these changes
Thanks!

2024-08-10 18:50 UTC, merged